### ISSUE TITLE
Decryption Error with Certain Secret Values

### ISSUE THREAD

**Issue by ntuckerp** [praetorian-inc/gato#42]
In an organization with both organization and repository secrets, Gato will fail to decrypt the final secrets blob for certain secret values. The stack trace is shown below:

```
2023-10-06T19:48:48.7558218Z ...cut blob...

[!] Decrypted and Decoded Secrets:

Traceback (most recent call last):
  File "/gato/venv/bin/gato", line 8, in <module>
    sys.exit(entry())
  File "/gato/venv/lib/python3.7/site-packages/gato/main.py", line 6, in entry
    sys.exit(cli.cli(sys.argv[1:]))
  File "/gato/venv/lib/python3.7/site-packages/gato/cli/cli.py", line 83, in cli
    arguments.func(arguments, subparsers)
  File "/gato/venv/lib/python3.7/site-packages/gato/cli/cli.py", line 202, in attack
    args.file_name
  File "/gato/venv/lib/python3.7/site-packages/gato/attack/attack.py", line 562, in secrets_dump
    padding.PKCS1v15()).decode()
  File "/gato/venv/lib/python3.7/site-packages/cryptography/hazmat/backends/openssl/rsa.py", line 446, in decrypt
    return _enc_dec_rsa(self._backend, self, ciphertext, padding)
  File "/gato/venv/lib/python3.7/site-packages/cryptography/hazmat/backends/openssl/rsa.py", line 97, in _enc_dec_rsa
    return _enc_dec_rsa_pkey_ctx(backend, key, data, padding_enum, padding)
  File "/gato/venv/lib/python3.7/site-packages/cryptography/hazmat/backends/openssl/rsa.py", line 163, in _enc_dec_rsa_pkey_ctx
    raise ValueError("Encryption/decryption failed.")
ValueError: Encryption/decryption failed.
```

Modifying the code to explicitly exclude the single "bad" secret works, indicating that the particular value is the problem. I originally thought the issue was with the `-e` switch in `echo`, but that's not the case.

For anyone dealing with this, you can modify `/attack/cicd_attack.py` line 89 and manually set the `secrets` list to only the values you care about.

**Comment by AdnaneKhan** [comment]
Thanks for the report! I will look into approaches to clean up the secret exfiltration. Perhaps it would be better to save them to a file and then encrypt that file to avoid any unusual behavior with formatting.

**Comment by mas0nd** [comment]
@santiago-praetorian Ran into this same issue today

**Comment by santiago-praetorian** [comment]
I tested #45, and it worked for me. I was able to pull all the secrets in one single run.

**Comment by AdnaneKhan** [comment]
Fixed in https://github.com/praetorian-inc/gato/pull/45, it will be merged into `dev` shortly.

Aiming for a version `1.5.1` bugfix update to main that includes #45, #46, and an update to clear other workflows for all attack modules (to prevent excess workflow executions).
